# Generated by Django 4.1.6 on 2023-02-07 13:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
