# Generated by Django 4.0.4 on 2023-02-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('nigeria', 'Nigeria')], max_length=200)),
                ('state', models.CharField(choices=[('ondo state', 'Ondo state')], max_length=200)),
                ('city', models.CharField(choices=[('akure', 'Akure')], max_length=200)),
                ('area', models.CharField(choices=[('alagbaka', 'Alagbaka'), ('arakale', 'Arakale'), ('araromi', 'Araromi'), ('futa north gate', 'Futa North Gate'), ('futa south gate', 'Futa South Gate'), ('igoba', 'Igoba'), ('ijapo', 'Ijapo'), ('ijoka', 'Ijoka'), ('irese', 'Irese'), ('isolo', 'Isolo'), ('oba-ile', 'Oba-ile'), ('oda', 'Oda'), ('oda road', 'Oda road'), ('oke-aro', 'Oke-aro'), ('oke-ijebu', 'Oke-Ijebu'), ('oke-ogba', 'Oke-Ogba'), ('okuta-elerin_nla', 'Okuta-elerin_nla'), ('onyarugbulem', 'Onyarugbulem'), ('orita', 'Orita-obele'), ('owode', 'Owode'), ('others', 'Others')], max_length=200)),
                ('street_name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
