# Generated by Django 4.1.6 on 2023-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='area',
            field=models.CharField(choices=[('alagbaka', 'Alagbaka'), ('arakale', 'Arakale'), ('araromi', 'Araromi'), ('futa north gate', 'Futa North Gate'), ('futa south gate', 'Futa South Gate'), ('igoba', 'Igoba'), ('ijapo', 'Ijapo'), ('ijoka', 'Ijoka'), ('irese', 'Irese'), ('isolo', 'Isolo'), ('oba-ile', 'Oba-ile'), ('oda', 'Oda'), ('oda road', 'Oda road'), ('oke-aro', 'Oke-aro'), ('oke-ijebu', 'Oke-Ijebu'), ('oke-ogba', 'Oke-Ogba'), ('okuta-elerin_nla', 'Okuta-elerin_nla'), ('onyarugbulem', 'Onyarugbulem'), ('orita', 'Orita-obele'), ('owode', 'Owode'), ('shagari', 'Shagari'), ('others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(choices=[('ondo', 'Ondo')], max_length=200),
        ),
    ]
