# Generated by Django 4.0.4 on 2022-12-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('food_item', models.CharField(max_length=30)),
                ('food_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('soup_item', models.CharField(max_length=30)),
                ('mini_box', models.IntegerField()),
                ('medium_box', models.IntegerField()),
                ('mega_box', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
