# Generated by Django 4.0.4 on 2022-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soup',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
