# Generated by Django 4.1.6 on 2023-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_food_food_price_alter_soup_medium_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='soup',
            name='medium_box',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='soup',
            name='mega_box',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='soup',
            name='mini_box',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
