# Generated by Django 4.1.6 on 2023-04-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_food_food_price_alter_soup_medium_box_and_more'),
        ('cart', '0002_cartitemssoup_cartitemsfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemsfood',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitemsfood',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='food_app.food'),
        ),
    ]
